/*
	A basic extension of the java.applet.Applet class
 */

import java.awt.*;
import java.applet.*;
import java.util.*;


public class Applet1 extends Applet
{
	double rate,year;
	static double fv,temp;
	static double pv=0.0;
	public void init()
	{
		// Take out this line if you don't use symantec.itools.net.RelativeURL or symantec.itools.awt.util.StatusScroller
		//symantec.itools.lang.Context.setApplet(this);
	
		// This code is automatically generated by Visual Cafe when you add
		// components to the visual environment. It instantiates and initializes
		// the components. To modify the code, only use code syntax that matches
		// what Visual Cafe can generate, or Visual Cafe may be unable to back
		// parse your Java file into its visual environment.
		//{{INIT_CONTROLS
		setLayout(null);
		setForeground(java.awt.Color.gray);
		setFont(new Font("Dialog", Font.PLAIN, 16));
		setSize(536,364);
		label1.setText("Present value");
		add(label1);
		label1.setForeground(java.awt.Color.magenta);
		label1.setFont(new Font("Dialog", Font.PLAIN, 18));
		label1.setBounds(192,24,120,27);
		label2.setText("To calculate present value of your Investment Yield");
		add(label2);
		label2.setForeground(java.awt.Color.blue);
		label2.setFont(new Font("Dialog", Font.BOLD, 16));
		label2.setBounds(60,72,404,25);
		label3.setText("Investment Yield (Future value):");
		add(label3);
		label3.setForeground(java.awt.Color.darkGray);
		label3.setFont(new Font("Dialog", Font.BOLD, 16));
		label3.setBounds(24,108,240,25);
		label4.setText(" Interest rate (in %):");
		add(label4);
		label4.setForeground(java.awt.Color.darkGray);
		label4.setFont(new Font("Dialog", Font.BOLD, 16));
		label4.setBounds(24,156,240,25);
		label5.setText("Years:");
		add(label5);
		label5.setForeground(java.awt.Color.darkGray);
		label5.setFont(new Font("Dialog", Font.BOLD, 16));
		label5.setBounds(24,204,240,25);
		label6.setText("Present value:");
		add(label6);
		label6.setForeground(java.awt.Color.darkGray);
		label6.setFont(new Font("Dialog", Font.BOLD, 16));
		label6.setBounds(24,252,240,25);
		button2.setLabel("Submit values");
		add(button2);
		button2.setBackground(java.awt.Color.lightGray);
		button2.setFont(new Font("Dialog", Font.BOLD, 12));
		button2.setBounds(396,204,111,21);
		add(textField1);
		textField1.setBounds(276,108,95,20);
		add(textField2);
		textField2.setBounds(276,156,95,20);
		add(textField3);
		textField3.setBounds(276,204,95,20);
		add(textField4);
		textField4.setBounds(276,252,95,20);
		//}}
	
		//{{REGISTER_LISTENERS
		SymAction lSymAction = new SymAction();
		button2.addActionListener(lSymAction);
		//}}
	}
	
	//{{DECLARE_CONTROLS
	java.awt.Label label1 = new java.awt.Label();
	java.awt.Label label2 = new java.awt.Label();
	java.awt.Label label3 = new java.awt.Label();
	java.awt.Label label4 = new java.awt.Label();
	java.awt.Label label5 = new java.awt.Label();
	java.awt.Label label6 = new java.awt.Label();
	java.awt.Button button2 = new java.awt.Button();
	java.awt.TextField textField1 = new java.awt.TextField();
	java.awt.TextField textField2 = new java.awt.TextField();
	java.awt.TextField textField3 = new java.awt.TextField();
	java.awt.TextField textField4 = new java.awt.TextField();
	//}}

	class SymAction implements java.awt.event.ActionListener
	{
		public void actionPerformed(java.awt.event.ActionEvent event)
		{
			Object object = event.getSource();
			if (object == button2)
				button2_ActionPerformed(event);
		}
	}

	void button2_ActionPerformed(java.awt.event.ActionEvent event)
	{
	    fv=(Double.valueOf(textField1.getText())).doubleValue();
	    rate=(Double.valueOf(textField2.getText())).doubleValue();
		year=(Double.valueOf(textField3.getText())).doubleValue();
		temp=1+(rate/100);
		temp=Math.pow(temp,year);
		pv=fv/temp;
		textField4.setText(Double.toString(pv));
	}
}
