/*
A basic extension of the com.sun.java.swing.JApplet class
*/
import java.awt.*;
import java.awt.event.*;
import java.applet.*;

public class applet1 extends applet implements ActionListener
{
	double rate,fv,yr,temp;
	static double pv=0.0;
	java.awt.Label label1 = new java.awt.Label();
	java.awt.Label label2 = new java.awt.Label();
	java.awt.Label label3 = new java.awt.Label();
	java.awt.TextField textField1 = new java.awt.TextField();
	java.awt.Label label4 = new java.awt.Label();
	java.awt.TextField textField2 = new java.awt.TextField();
	java.awt.Label label5 = new java.awt.Label();
	java.awt.TextField textField3 = new java.awt.TextField();
	java.awt.Label label6 = new java.awt.Label();
	java.awt.TextField textField4 = new java.awt.TextField();
	java.awt.Button button1 = new java.awt.Button();
	public void init()
	{
		// Take out this line if you don't use symantec.itools.net.RelativeURL or symantec.itools.awt.util.StatusScroller
		symantec.itools.lang.Context.setApplet(this);
		
		// This line prevents the "Swing: checked access to system event queue" message seen in some browsers.
		getRootPane().putClientProperty("defeatSystemEventQueueCheck", Boolean.TRUE);
		
		// This code is automatically generated by Visual Cafe when you add
		// components to the visual environment. It instantiates and initializes
		// the components. To modify the code, only use code syntax that matches
		// what Visual Cafe can generate, or Visual Cafe may be unable to back
		// parse your Java file into its visual environment.
		//{{INIT_CONTROLS
		getContentPane().setLayout(null);
		getContentPane().setFont(new Font("Dialog", Font.BOLD, 12));
		setSize(537,363);
		label1.setText(" Present Value");
		label1.setAlignment(java.awt.Label.CENTER);
		getContentPane().add(label1);
		label1.setForeground(java.awt.Color.magenta);
		label1.setFont(new Font("SansSerif", Font.BOLD, 16));
		label1.setBounds(156,12,120,24);
		label2.setText(" To calculate the value of your Investment Yield ");
		getContentPane().add(label2);
		label2.setForeground(java.awt.Color.blue);
		label2.setFont(new Font("Dialog", Font.PLAIN, 16));
		label2.setBounds(24,60,336,24);
		label3.setText(" Investment Yield :");
		getContentPane().add(label3);
		label3.setFont(new Font("Dialog", Font.PLAIN, 16));
		label3.setBounds(24,96,120,24);
		getContentPane().add(textField1);
		textField1.setBounds(180,96,92,17);
		label4.setText(" Interest Rate (in %):");
		getContentPane().add(label4);
		label4.setFont(new Font("Dialog", Font.PLAIN, 14));
		label4.setBounds(24,132,144,24);
		getContentPane().add(textField2);
		textField2.setBounds(180,132,92,17);
		label5.setText(" Number of years:");
		getContentPane().add(label5);
		label5.setFont(new Font("Dialog", Font.PLAIN, 14));
		label5.setBounds(24,168,144,24);
		getContentPane().add(textField3);
		textField3.setBounds(180,168,92,17);
		label6.setText(" The Present Value is:");
		getContentPane().add(label6);
		label6.setFont(new Font("Dialog", Font.PLAIN, 14));
		label6.setBounds(24,228,144,24);
		getContentPane().add(textField4);
		textField4.setBounds(180,228,92,17);
		button1.setLabel("Submit the Data");
		getContentPane().add(button1);
		button1.setBackground(java.awt.Color.lightGray);
		button1.setBounds(300,168,96,24);
		//}}
	
		//{{REGISTER_LISTENERS
		SymAction lSymAction = new SymAction();
		button1.addActionListener(lSymAction);
		//}}
	}

	//{{DECLARE_CONTROLS
	
	

	class SymAction implements java.awt.event.ActionListener
	{
		public void actionPerformed(java.awt.event.ActionEvent event)
		{
			Object object = event.getSource();
			if (object == button1)
				button1_ActionPerformed(event);
		}
	}

	void button1_ActionPerformed(java.awt.event.ActionEvent event)
	{
	
	    fv=parseDouble(event.textField1.getText());
	    try{rate=parseDouble(event.textField2.getText());
	    yr=parseDouble(event.textField3.getText());
	    }catch(NumberFormatException ne){
	        System.out.println("Not Converting");
	    }
	    temp=pow(rate,yr);
	    pv=(fv/temp);
	    textField4.setText(toString(pv));
	    }
        //}}
    
			 
	}
}
